{"url":"https://api.github.com/repos/willmcgugan/rich/issues/68","repository_url":"https://api.github.com/repos/willmcgugan/rich","labels_url":"https://api.github.com/repos/willmcgugan/rich/issues/68/labels{/name}","comments_url":"https://api.github.com/repos/willmcgugan/rich/issues/68/comments","events_url":"https://api.github.com/repos/willmcgugan/rich/issues/68/events","html_url":"https://github.com/willmcgugan/rich/issues/68","id":616802172,"node_id":"MDU6SXNzdWU2MTY4MDIxNzI=","number":68,"title":"Can't print Table in a Gitlab CI runner","user":{"login":"beojan","id":3727925,"node_id":"MDQ6VXNlcjM3Mjc5MjU=","avatar_url":"https://avatars0.githubusercontent.com/u/3727925?v=4","gravatar_id":"","url":"https://api.github.com/users/beojan","html_url":"https://github.com/beojan","followers_url":"https://api.github.com/users/beojan/followers","following_url":"https://api.github.com/users/beojan/following{/other_user}","gists_url":"https://api.github.com/users/beojan/gists{/gist_id}","starred_url":"https://api.github.com/users/beojan/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/beojan/subscriptions","organizations_url":"https://api.github.com/users/beojan/orgs","repos_url":"https://api.github.com/users/beojan/repos","events_url":"https://api.github.com/users/beojan/events{/privacy}","received_events_url":"https://api.github.com/users/beojan/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2020-05-12T16:42:20Z","updated_at":"2020-05-13T11:31:37Z","closed_at":"2020-05-13T11:31:37Z","author_association":"NONE","active_lock_reason":null,"body":"When running under a Gitlab CI runner, I get the following error when I print a `Table`:\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \".ci/report.py\", line 33, in <module>\r\n    cons.print(table)\r\n  File \"/home/sftnight/.local/lib/python3.6/site-packages/rich/console.py\", line 724, in print\r\n    render(renderable, render_options), self.get_style(style)\r\n  File \"/home/sftnight/.local/lib/python3.6/site-packages/rich/console.py\", line 347, in __exit__\r\n    self._exit_buffer()\r\n  File \"/home/sftnight/.local/lib/python3.6/site-packages/rich/console.py\", line 338, in _exit_buffer\r\n    self._check_buffer()\r\n  File \"/home/sftnight/.local/lib/python3.6/site-packages/rich/console.py\", line 804, in _check_buffer\r\n    self.file.write(text)\r\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 0-50: ordinal not in range(128)\r\n```","closed_by":{"login":"willmcgugan","id":554369,"node_id":"MDQ6VXNlcjU1NDM2OQ==","avatar_url":"https://avatars3.githubusercontent.com/u/554369?v=4","gravatar_id":"","url":"https://api.github.com/users/willmcgugan","html_url":"https://github.com/willmcgugan","followers_url":"https://api.github.com/users/willmcgugan/followers","following_url":"https://api.github.com/users/willmcgugan/following{/other_user}","gists_url":"https://api.github.com/users/willmcgugan/gists{/gist_id}","starred_url":"https://api.github.com/users/willmcgugan/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/willmcgugan/subscriptions","organizations_url":"https://api.github.com/users/willmcgugan/orgs","repos_url":"https://api.github.com/users/willmcgugan/repos","events_url":"https://api.github.com/users/willmcgugan/events{/privacy}","received_events_url":"https://api.github.com/users/willmcgugan/received_events","type":"User","site_admin":false},"performed_via_github_app":null}