{"url":"https://api.github.com/repos/willmcgugan/rich/issues/330","repository_url":"https://api.github.com/repos/willmcgugan/rich","labels_url":"https://api.github.com/repos/willmcgugan/rich/issues/330/labels{/name}","comments_url":"https://api.github.com/repos/willmcgugan/rich/issues/330/comments","events_url":"https://api.github.com/repos/willmcgugan/rich/issues/330/events","html_url":"https://github.com/willmcgugan/rich/issues/330","id":714297345,"node_id":"MDU6SXNzdWU3MTQyOTczNDU=","number":330,"title":"[BUG] Colors doesn't work on Git Bash","user":{"login":"naveen521kk","id":49693820,"node_id":"MDQ6VXNlcjQ5NjkzODIw","avatar_url":"https://avatars1.githubusercontent.com/u/49693820?v=4","gravatar_id":"","url":"https://api.github.com/users/naveen521kk","html_url":"https://github.com/naveen521kk","followers_url":"https://api.github.com/users/naveen521kk/followers","following_url":"https://api.github.com/users/naveen521kk/following{/other_user}","gists_url":"https://api.github.com/users/naveen521kk/gists{/gist_id}","starred_url":"https://api.github.com/users/naveen521kk/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/naveen521kk/subscriptions","organizations_url":"https://api.github.com/users/naveen521kk/orgs","repos_url":"https://api.github.com/users/naveen521kk/repos","events_url":"https://api.github.com/users/naveen521kk/events{/privacy}","received_events_url":"https://api.github.com/users/naveen521kk/received_events","type":"User","site_admin":false},"labels":[{"id":2200581776,"node_id":"MDU6TGFiZWwyMjAwNTgxNzc2","url":"https://api.github.com/repos/willmcgugan/rich/labels/Needs%20triage","name":"Needs triage","color":"bfdadc","default":false,"description":""}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":10,"created_at":"2020-10-04T11:53:12Z","updated_at":"2020-10-04T14:22:24Z","closed_at":"2020-10-04T14:22:24Z","author_association":"NONE","active_lock_reason":null,"body":"**Describe the bug**\r\nI am Windows 7 and install python 3.8 where I used Git Bash(For a change.). I typed the following things in terminal where it should show the image as in ReadMe. \r\nWhile I get a long error Message of UnicodeEncodeError\r\nThe output I get is\r\n```\r\n                                 Rich features\r\n\r\n              Colors 256 colors or 16.7 million colors (if supported by your\r\n                     terminal).\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n              Styles All ansi styles: bold, dim, italic, underline,\r\n                     strikethrough, reverse, and even blink.\r\n\r\n                Text Word wrap text. Justify left, center, right or full.\r\n\r\n                     Lorem ipsum    Lorem ipsum     Lorem ipsum Lorem    ipsum\r\n                     dolor sit       dolor sit        dolor sit dolor      sit\r\n                     amet,             amet,              amet, amet,\r\n                     consectetur    consectetur     consectetur consectetur\r\n                     adipiscing     adipiscing       adipiscing adipiscing\r\n                     elit. Quisque elit. Quisque  elit. Quisque elit.  Quisque\r\n                     in metus sed  in metus sed    in metus sed in  metus  sed\r\n                     sapien           sapien             sapien sapien\r\n                     ultricies       ultricies        ultricies ultricies\r\n                     pretium a at  pretium a at    pretium a at pretium  a  at\r\n                     justo.           justo.             justo. justo.\r\n                     Maecenas        Maecenas          Maecenas Maecenas\r\n                     luctus velit  luctus velit    luctus velit luctus   velit\r\n                     et auctor       et auctor        et auctor et      auctor\r\n                     maximus.        maximus.    maximus. Donec maximus. Donec\r\n                     Donec             Donec       faucibus vel faucibus   vel\r\n                     faucibus vel  faucibus vel         arcu id arcu        id\r\n                     arcu id          arcu id          pretium. pretium.\r\n                     pretium.        pretium.\r\n\r\n         CJK support Traceback (most recent call last):\r\n  File \"C:\\Users\\Naveen User\\AppData\\Local\\Programs\\Python\\Python38\\lib\\runpy.py\", line 194, in _run_module_as_main\r\n    return _run_code(code, main_globals, None,\r\n  File \"C:\\Users\\Naveen User\\AppData\\Local\\Programs\\Python\\Python38\\lib\\runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"C:\\Users\\Naveen User\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\rich\\__main__.py\", line 188, in <module>\r\n    print(line)\r\n  File \"C:\\Users\\Naveen User\\AppData\\Roaming\\Python\\Python38\\site-packages\\colorama\\ansitowin32.py\", line 41, in write\r\n    self.__convertor.write(text)\r\n  File \"C:\\Users\\Naveen User\\AppData\\Roaming\\Python\\Python38\\site-packages\\colorama\\ansitowin32.py\", line 162, in write\r\n    self.write_and_convert(text)\r\n  File \"C:\\Users\\Naveen User\\AppData\\Roaming\\Python\\Python38\\site-packages\\colorama\\ansitowin32.py\", line 187, in write_and_convert\r\n    self.write_plain_text(text, cursor, start)\r\n  File \"C:\\Users\\Naveen User\\AppData\\Roaming\\Python\\Python38\\site-packages\\colorama\\ansitowin32.py\", line 195, in write_plain_text\r\n    self.wrapped.write(text[start:end])\r\n  File \"C:\\Users\\Naveen User\\AppData\\Local\\Programs\\Python\\Python38\\lib\\encodings\\cp1252.py\", line 19, in encode\r\n    return codecs.charmap_encode(input,self.errors,encoding_table)[0]\r\nUnicodeEncodeError: 'charmap' codec can't encode characters in position 0-31: character maps to <undefined>\r\n```\r\nand no colours in it.\r\n![image](https://user-images.githubusercontent.com/49693820/95014592-7fc4ce80-0665-11eb-9fbd-02d2afe66a57.png)\r\nAlso, when I run `py -m rich.logging`\r\nI get a ZeroDivisionError.\r\n```$ py -m rich.logging\r\n[17:18:29] INFO     Server starting...                           logging.py:155\r\n           INFO     Listening on http://127.0.0.1:8080           logging.py:156\r\n[17:18:30] INFO     GET /index.html 200 1298                     logging.py:159\r\n           INFO     GET /imgs/backgrounds/back1.jpg 200 54386    logging.py:160\r\n           INFO     GET /css/styles.css 200 54386                logging.py:161\r\n           WARNING  GET /favicon.ico 404 242                     logging.py:162\r\n[17:18:31] DEBUG    JSONRPC request                              logging.py:165\r\n                    --> {'version': '1.1', 'method':\r\n                    'confirmFruitPurchase', 'params': [['apple',\r\n                    'orange', 'mangoes', 'pomelo'], 1.123],\r\n                    'id': '194521489'}\r\n                    <-- {'version': '1.1', 'result': True,\r\n                    'error': None, 'id': '194521489'}\r\n           DEBUG    Loading configuration file /adasd/asdasd/qeq logging.py:175\r\n                    we/qwrqwrqwr/sdgsdgsdg/werwerwer/dfgerert/er\r\n                    tertert/ertetert/werwerwer\r\n           ERROR    Unable to find 'pomelo' in database!         logging.py:178\r\n           INFO     POST /jsonrpc/ 200 65532                     logging.py:179\r\n           INFO     POST /admin/ 401 42234                       logging.py:180\r\n           WARNING  password was rejected for admin site.        logging.py:181\r\n           ERROR    An error of some kind occurred!              logging.py:185\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\Naveen User\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\rich\\logging.py\", line 183, in <module>\r\n    1 / 0\r\nZeroDivisionError: division by zero\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\Naveen User\\AppData\\Local\\Programs\\Python\\Python38\\lib\\runpy.py\", line 194, in _run_module_as_main\r\n    return _run_code(code, main_globals, None,\r\n  File \"C:\\Users\\Naveen User\\AppData\\Local\\Programs\\Python\\Python38\\lib\\runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"C:\\Users\\Naveen User\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\rich\\logging.py\", line 185, in <module>\r\n    log.exception(\"An error of some kind occurred!\")\r\n  File \"C:\\Users\\Naveen User\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1469, in exception\r\n    self.error(msg, *args, exc_info=exc_info, **kwargs)\r\n  File \"C:\\Users\\Naveen User\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1463, in error\r\n    self._log(ERROR, msg, args, **kwargs)\r\n  File \"C:\\Users\\Naveen User\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1577, in _log\r\n    self.handle(record)\r\n  File \"C:\\Users\\Naveen User\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1587, in handle\r\n    self.callHandlers(record)\r\n  File \"C:\\Users\\Naveen User\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 1649, in callHandlers\r\n    hdlr.handle(record)\r\n  File \"C:\\Users\\Naveen User\\AppData\\Local\\Programs\\Python\\Python38\\lib\\logging\\__init__.py\", line 950, in handle\r\n    self.emit(record)\r\n  File \"C:\\Users\\Naveen User\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\rich\\logging.py\", line 128, in emit\r\n    self.console.print(\r\n  File \"C:\\Users\\Naveen User\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\rich\\console.py\", line 1028, in print\r\n    self._buffer.extend(new_segments)\r\n  File \"C:\\Users\\Naveen User\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\rich\\console.py\", line 507, in __exit__\r\n    self._exit_buffer()\r\n  File \"C:\\Users\\Naveen User\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\rich\\console.py\", line 485, in _exit_buffer\r\n    self._check_buffer()\r\n  File \"C:\\Users\\Naveen User\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\rich\\console.py\", line 1156, in _check_buffer\r\n    write(line)\r\n  File \"C:\\Users\\Naveen User\\AppData\\Roaming\\Python\\Python38\\site-packages\\colorama\\ansitowin32.py\", line 41, in write\r\n    self.__convertor.write(text)\r\n  File \"C:\\Users\\Naveen User\\AppData\\Roaming\\Python\\Python38\\site-packages\\colorama\\ansitowin32.py\", line 162, in write\r\n    self.write_and_convert(text)\r\n  File \"C:\\Users\\Naveen User\\AppData\\Roaming\\Python\\Python38\\site-packages\\colorama\\ansitowin32.py\", line 190, in write_and_convert\r\n    self.write_plain_text(text, cursor, len(text))\r\n  File \"C:\\Users\\Naveen User\\AppData\\Roaming\\Python\\Python38\\site-packages\\colorama\\ansitowin32.py\", line 195, in write_plain_text\r\n    self.wrapped.write(text[start:end])\r\n  File \"C:\\Users\\Naveen User\\AppData\\Local\\Programs\\Python\\Python38\\lib\\encodings\\cp1252.py\", line 19, in encode\r\n    return codecs.charmap_encode(input,self.errors,encoding_table)[0]\r\nUnicodeEncodeError: 'charmap' codec can't encode characters in position 20-23: character maps to <undefined>\r\n*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***\r\n```\r\n![image](https://user-images.githubusercontent.com/49693820/95014653-dc27ee00-0665-11eb-82ac-9943341a4487.png)\r\nBtw, everything is fine with CMD or Powershell.\r\n\r\n**To Reproduce**\r\nRunning `py -m rich` in Git Bash For Windows shows these errors.\r\n\r\n**Platform**\r\nI am on Windows 7. The terminal I am using is Git bash. The rich version is `rich==8.0.0`","closed_by":{"login":"willmcgugan","id":554369,"node_id":"MDQ6VXNlcjU1NDM2OQ==","avatar_url":"https://avatars3.githubusercontent.com/u/554369?v=4","gravatar_id":"","url":"https://api.github.com/users/willmcgugan","html_url":"https://github.com/willmcgugan","followers_url":"https://api.github.com/users/willmcgugan/followers","following_url":"https://api.github.com/users/willmcgugan/following{/other_user}","gists_url":"https://api.github.com/users/willmcgugan/gists{/gist_id}","starred_url":"https://api.github.com/users/willmcgugan/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/willmcgugan/subscriptions","organizations_url":"https://api.github.com/users/willmcgugan/orgs","repos_url":"https://api.github.com/users/willmcgugan/repos","events_url":"https://api.github.com/users/willmcgugan/events{/privacy}","received_events_url":"https://api.github.com/users/willmcgugan/received_events","type":"User","site_admin":false},"performed_via_github_app":null}