{"url":"https://api.github.com/repos/willmcgugan/rich/issues/58","repository_url":"https://api.github.com/repos/willmcgugan/rich","labels_url":"https://api.github.com/repos/willmcgugan/rich/issues/58/labels{/name}","comments_url":"https://api.github.com/repos/willmcgugan/rich/issues/58/comments","events_url":"https://api.github.com/repos/willmcgugan/rich/issues/58/events","html_url":"https://github.com/willmcgugan/rich/issues/58","id":613827797,"node_id":"MDU6SXNzdWU2MTM4Mjc3OTc=","number":58,"title":"does not work with PyInstaller","user":{"login":"frankenstein91","id":2527348,"node_id":"MDQ6VXNlcjI1MjczNDg=","avatar_url":"https://avatars3.githubusercontent.com/u/2527348?v=4","gravatar_id":"","url":"https://api.github.com/users/frankenstein91","html_url":"https://github.com/frankenstein91","followers_url":"https://api.github.com/users/frankenstein91/followers","following_url":"https://api.github.com/users/frankenstein91/following{/other_user}","gists_url":"https://api.github.com/users/frankenstein91/gists{/gist_id}","starred_url":"https://api.github.com/users/frankenstein91/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/frankenstein91/subscriptions","organizations_url":"https://api.github.com/users/frankenstein91/orgs","repos_url":"https://api.github.com/users/frankenstein91/repos","events_url":"https://api.github.com/users/frankenstein91/events{/privacy}","received_events_url":"https://api.github.com/users/frankenstein91/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":9,"created_at":"2020-05-07T07:11:00Z","updated_at":"2020-05-07T11:50:48Z","closed_at":"2020-05-07T11:50:48Z","author_association":"NONE","active_lock_reason":null,"body":"I wanted to use the nicer traceback of this application for one of my projects. Unfortunately I can't get this to run on Windows. I have to put the application into an exe and get problems with the import of rich.\r\nOnce I insert this source code into my program, I cannot start it after the packing process.\r\n\r\n```\r\nfrom rich.traceback import install\r\ninstall()\r\n```\r\n\r\nI get the following error message on the console.\r\n```\r\nTraceback (most recent call last):\r\n  File \"venv\\Lib\\site-packages\\PyInstaller\\loader\\rthooks\\pyi_rth_pkgres.py\", line 13, in <module>\r\n    import pkg_resources as res\r\n  File \"c:\\users\\vmuser\\pycharmprojects\\logdings\\venv\\lib\\site-packages\\PyInstaller\\loader\\pyimod03_importers.py\", line 623, in exec_module\r\n    exec(bytecode, module.__dict__)\r\n  File \"lib\\site-packages\\pkg_resources\\__init__.py\", line 86, in <module>\r\nModuleNotFoundError: No module named 'pkg_resources.py2_warn'\r\n[5020] Failed to execute script pyi_rth_pkgres\r\n\r\n```\r\n\r\nSince @pyinstaller is a very big project, I wanted to ask here first how to get it running.","closed_by":{"login":"willmcgugan","id":554369,"node_id":"MDQ6VXNlcjU1NDM2OQ==","avatar_url":"https://avatars3.githubusercontent.com/u/554369?v=4","gravatar_id":"","url":"https://api.github.com/users/willmcgugan","html_url":"https://github.com/willmcgugan","followers_url":"https://api.github.com/users/willmcgugan/followers","following_url":"https://api.github.com/users/willmcgugan/following{/other_user}","gists_url":"https://api.github.com/users/willmcgugan/gists{/gist_id}","starred_url":"https://api.github.com/users/willmcgugan/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/willmcgugan/subscriptions","organizations_url":"https://api.github.com/users/willmcgugan/orgs","repos_url":"https://api.github.com/users/willmcgugan/repos","events_url":"https://api.github.com/users/willmcgugan/events{/privacy}","received_events_url":"https://api.github.com/users/willmcgugan/received_events","type":"User","site_admin":false},"performed_via_github_app":null}