{"url":"https://api.github.com/repos/willmcgugan/rich/issues/497","repository_url":"https://api.github.com/repos/willmcgugan/rich","labels_url":"https://api.github.com/repos/willmcgugan/rich/issues/497/labels{/name}","comments_url":"https://api.github.com/repos/willmcgugan/rich/issues/497/comments","events_url":"https://api.github.com/repos/willmcgugan/rich/issues/497/events","html_url":"https://github.com/willmcgugan/rich/issues/497","id":767467560,"node_id":"MDU6SXNzdWU3Njc0Njc1NjA=","number":497,"title":"[BUG] Exceptions inside progress","user":{"login":"tgdn","id":480050,"node_id":"MDQ6VXNlcjQ4MDA1MA==","avatar_url":"https://avatars2.githubusercontent.com/u/480050?v=4","gravatar_id":"","url":"https://api.github.com/users/tgdn","html_url":"https://github.com/tgdn","followers_url":"https://api.github.com/users/tgdn/followers","following_url":"https://api.github.com/users/tgdn/following{/other_user}","gists_url":"https://api.github.com/users/tgdn/gists{/gist_id}","starred_url":"https://api.github.com/users/tgdn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/tgdn/subscriptions","organizations_url":"https://api.github.com/users/tgdn/orgs","repos_url":"https://api.github.com/users/tgdn/repos","events_url":"https://api.github.com/users/tgdn/events{/privacy}","received_events_url":"https://api.github.com/users/tgdn/received_events","type":"User","site_admin":false},"labels":[{"id":2200581776,"node_id":"MDU6TGFiZWwyMjAwNTgxNzc2","url":"https://api.github.com/repos/willmcgugan/rich/labels/Needs%20triage","name":"Needs triage","color":"bfdadc","default":false,"description":""}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":6,"created_at":"2020-12-15T11:02:55Z","updated_at":"2020-12-16T09:39:27Z","closed_at":"2020-12-16T09:39:27Z","author_association":"NONE","active_lock_reason":null,"body":"I'm not sure this is a bug or if I'm simply unable to find the solution to my problem.\r\n\r\nSorry in advance if this is a duplicate or if it is documented, but I really can't seem to find a solution.\r\n\r\n## How do I print/handle/see exceptions when using progress?\r\n\r\nI've tried:\r\n\r\n```python\r\nprogress = Progress(\r\n    redirect_stderr=False,\r\n)\r\n\r\n# or\r\n\r\nprogress = Progress(\r\n    redirect_stderr=True,\r\n)\r\n\r\nwith progress:\r\n    raise Exception('hello')\r\n```\r\n\r\nI have even tried using my own Console, nothing happens, the exception is just invisible, which makes the code within `with` impossible to debug.\r\n\r\n\r\n**Platform**\r\nmacOS 10.15.5\r\nrich==9.3.0\r\nPython 3.8.6\r\n\r\nThank you in advance.\r\n","closed_by":{"login":"willmcgugan","id":554369,"node_id":"MDQ6VXNlcjU1NDM2OQ==","avatar_url":"https://avatars3.githubusercontent.com/u/554369?v=4","gravatar_id":"","url":"https://api.github.com/users/willmcgugan","html_url":"https://github.com/willmcgugan","followers_url":"https://api.github.com/users/willmcgugan/followers","following_url":"https://api.github.com/users/willmcgugan/following{/other_user}","gists_url":"https://api.github.com/users/willmcgugan/gists{/gist_id}","starred_url":"https://api.github.com/users/willmcgugan/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/willmcgugan/subscriptions","organizations_url":"https://api.github.com/users/willmcgugan/orgs","repos_url":"https://api.github.com/users/willmcgugan/repos","events_url":"https://api.github.com/users/willmcgugan/events{/privacy}","received_events_url":"https://api.github.com/users/willmcgugan/received_events","type":"User","site_admin":false},"performed_via_github_app":null}